### ISSUE TITLE
when changed to classfication, threws ValueError

### ISSUE THREAD

**Issue by hittle2015** [lovecambi/qebrain#10]
I changed the following lines  following your recommendation:
          sent_label =tf.cast(self.label, tf.int32) ###### line 1345
          sent_loss += tf.nn.sparse_softmax_cross_entropy_with_logits(labels=self.label,logits=sent_logits) ##1346
Then I got the following error:
..............................................................
Traceback (most recent call last):
  File "qe_model.py", line 2193, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "qe_model.py", line 2186, in main
    run_main(FLAGS, default_hparams, train, inference)
  File "qe_model.py", line 2181, in run_main
    train_fn(hparams, target_session=target_session)
  File "qe_model.py", line 1715, in train
    train_model = create_train_model(model_creator, hparams, scope)
  File "qe_model.py", line 751, in create_train_model
    scope=scope)
  File "qe_model.py", line 1107, in __init__
    res = self.build_graph(hparams, scope=scope)
  File "qe_model.py", line 1197, in build_graph
    loss = self._compute_est_loss(est_logits_list)
  File "qe_model.py", line 1348, in _compute_est_loss
    sent_loss += tf.nn.sparse_softmax_cross_entropy_with_logits(labels=self.label,logits=sent_logits)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2049, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 7520, in sparse_softmax_cross_entropy_with_logits
    labels=labels, name=name)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'labels' has DataType float32 not in list of allowed values: int32, int64

**Comment by lovecambi** [comment]
sent_label =tf.cast(self.label, tf.int32) ###### line 1345
sent_loss += tf.nn.sparse_softmax_cross_entropy_with_logits(labels=sent_label,logits=sent_logits)

**Comment by hittle2015** [comment]
Thanks, however, I got this when  the corresponding lines are changed.
.................
  File "qe_model.py", line 2193, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "qe_model.py", line 2186, in main
    run_main(FLAGS, default_hparams, train, inference)
  File "qe_model.py", line 2181, in run_main
    train_fn(hparams, target_session=target_session)
  File "qe_model.py", line 1715, in train
    train_model = create_train_model(model_creator, hparams, scope)
  File "qe_model.py", line 751, in create_train_model
    scope=scope)
  File "qe_model.py", line 1153, in __init__
    colocate_gradients_with_ops=True)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 155, in optimize_loss
    contrib_framework.assert_scalar(loss)
  File "/home/yuyuan/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 1264, in assert_scalar
    % (tensor.name, shape))
ValueError: Expected scalar shape for transformerpredictor/add_2:0, saw shape: (?,).

**Comment by lovecambi** [comment]
you need to apply tf.reduce_mean to the batch loss to make the loss as a scalar.
