### ISSUE TITLE
Variable transformerpredictor/estimator/sent_generator/dense/kernel already exists, disallowed

### ISSUE THREAD

**Issue by dimitarsh1** [lovecambi/qebrain#4]
Hello,
I have the following issue with the qe_model.py

```
...
# Creating new directory ./saved_qe_model_en_de/avg_checkpoints for saving averaged checkpoints.
# Reading and averaging variables in checkpoints:
    ./saved_qe_model_en_de/qe.ckpt-1000
    ./saved_qe_model_en_de/qe.ckpt-2000
    ./saved_qe_model_en_de/qe.ckpt-3000
    ./saved_qe_model_en_de/qe.ckpt-4000
    ./saved_qe_model_en_de/qe.ckpt-5000
Traceback (most recent call last):
  File "qe_model.py", line 2191, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "qe_model.py", line 2184, in main
    run_main(FLAGS, default_hparams, train, inference)
  File "qe_model.py", line 2179, in run_main
    train_fn(hparams, target_session=target_session)
  File "qe_model.py", line 1803, in train
    run_avg_external_eval(infer_model, infer_sess, model_dir, hparams, summary_writer, global_step)
  File "qe_model.py", line 1624, in run_avg_external_eval
    avg_model_dir = avg_checkpoints(model_dir, hparams.num_keep_ckpts, global_step, global_step_name)
  File "qe_model.py", line 923, in avg_checkpoints
    tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for v in var_values]
  File "qe_model.py", line 923, in <listcomp>
    tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for v in var_values]
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/dimitarsh1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 861, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable transformerpredictor/estimator/sent_generator/dense/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "qe_model.py", line 923, in <listcomp>
    tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for v in var_values]
  File "qe_model.py", line 923, in avg_checkpoints
    tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for v in var_values]
  File "qe_model.py", line 1624, in run_avg_external_eval
    avg_model_dir = avg_checkpoints(model_dir, hparams.num_keep_ckpts, global_step, global_step_name)
```

Cheers,
Dimitar

**Comment by lovecambi** [comment]
```
tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for v in var_values]
```
should be
```
tf_vars = [tf.get_variable(name, shape=var_values[name].shape, dtype=var_dtypes[name]) for name in var_values]
```
fixed it.
