### ISSUE TITLE
print_out function in expert_model report attribute error

### ISSUE THREAD

**Issue by hittle2015** [lovecambi/qebrain#6]
When I finished training the expert model the following line (41) complains:

f.write (s.encode('utf8')) 
saying float has no attribute of write.

**Comment by lovecambi** [comment]
> When I finished training the expert model the following line (41) complains:
> 
> f.write (s.encode('utf8'))
> saying float has no attribute of write.

can you copy the whole error message?

**Comment by hittle2015** [comment]
Hoop, I opened the expert_model.py file to look into the lines and cannot go back to the screen now.

**Comment by fredblain** [comment]
Hi, 
I've faced the same issue, here is the error message:
> Traceback (most recent call last):
>   File "expert_model.py", line 1691, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/home/fblain/.virtualenvs/qebrain/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "expert_model.py", line 1684, in main
>     run_main(FLAGS, default_hparams, train)
>   File "expert_model.py", line 1679, in run_main
>     train_fn(hparams, target_session=target_session)
>   File "expert_model.py", line 1396, in train
>     print_out("# Done training!", time.time() - start_train_time)
>   File "expert_model.py", line 41, in print_out
>     f.write(s.encode("utf-8"))
> AttributeError: 'float' object has no attribute 'write

The problem lies in line 1396. @lovecambi, it's just (somehow) a typo creating the bug. I won't make a PR for it, but let you update the code directly. Something like this should do:
`print_out("# Done training! (time: %.2fs)" % (time.time() - start_train_time))`

Cheers,
